### ISSUE TITLE
Supporting project using go mod?

### ISSUE THREAD

**Issue by kevinho** [fjl/gencodec#10]
We have a project using go mod, and not under gopath, when i use this tool, it throws:

```
can't find package containing mypackage/*.go
file.go:66: running "gencodec": exit status 1
```

**Comment by Nanyan** [comment]
It seems that the author no longer maintains this project.  

Try this fork: [github.com/youchainhq/gencodec](https://github.com/youchainhq/gencodec)

**Comment by kevinho** [comment]
great job

**Comment by fjl** [comment]
I am still maintaining this project!

**Comment by Nanyan** [comment]
Great! I will create a pull request soon.

**Comment by fjl** [comment]
Sorry, have already pushed the changes to make go module work.

**Comment by fjl** [comment]
Please try the master branch.
